### ISSUE TITLE
Wrong GitHub Repo

### ISSUE THREAD

**Issue by zoffixznet** [perlancar/perl-Ubuntu-Releases#1]
FYI: the current version on CPAN links to an incorrect GitHub repo.

The link points to https://github.com/sharyanto/perl-Ubuntu-Releases

**Comment by perlancar** [comment]
Sorry, missed this PR/issue (didn't receive notification from GitHub).

Yes, I'll need to re-release my distros to update the information. I think I'll do this on an as-needed basis, instead of spamming PAUSE with lots of releases.

At least GitHub redirects the URL to the correct one.

I'm closing this issue for now.
